name: Nio-Block-Replace
version: 0.1
main: NioBlockReplace
description: Adds the ability to customize drops.
api-version: 1.13
commands:
  nioreplace:
      description: Used to replace blocks.
      usage: /nioreplace <world> <x1> <y1> <z1> <x2> <y2> <z2> <target block:replacingblock:chance>...
      permission: nioblockreplace.blockreplace
      permission-message: You don't have permission to use that command.
  nioreplacecancel:
      description: Used to cancel the replacement of blocks.
      usage: /nioreplacecancel
      permission: nioblockreplace.blockreplacecancel
      permission-message: You don't have permission to use that command.
  nioreplacereload:
      description: Used to reload the plugin.
      permission: nioblockreplace.reload
      permission-message: You don't have permission to use that command.